# Generated by Django 2.0.3 on 2018-03-23 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_auto_20180323_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadesfederacao',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
